
CREATE TABLE tipo_sangre (
    id_tipo_sangre    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo              VARCHAR2(5) UNIQUE NOT NULL
);

-- Tabla 2: Donante
CREATE TABLE donante (
    id_donante        VARCHAR2(20) PRIMARY KEY,
    nombre            VARCHAR2(50),
    apellido          VARCHAR2(50),
    direccion         VARCHAR2(100),
    fecha_nacimiento  DATE,
    sexo              VARCHAR2(1),
    telefono          VARCHAR2(20),
    correo            VARCHAR2(100),
    id_tipo_sangre    NUMBER,
    CONSTRAINT fk_donante_tipo_sangre FOREIGN KEY (id_tipo_sangre)
        REFERENCES tipo_sangre(id_tipo_sangre)
);

-- Tabla 3: Centro Donacion
CREATE TABLE centro_donacion (
    id_centro         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(100),
    ubicacion         VARCHAR2(150),
    tipo              VARCHAR2(50)
);

-- Tabla 4: Rol
CREATE TABLE rol (
    id_rol            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol        VARCHAR2(50),
    descripcion       VARCHAR2(255)
);

-- Tabla 5: Usuario
CREATE TABLE usuario (
    id_usuario        VARCHAR2(20) PRIMARY KEY,
    nombre_usuario    VARCHAR2(50) UNIQUE,
    correo            VARCHAR2(100),
    contrasena        VARCHAR2(100),
    estado            VARCHAR2(10),
    id_rol            NUMBER,
    CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol)
        REFERENCES rol(id_rol)
);

-- Tabla 6: Donación
CREATE TABLE donacion (
    id_donacion       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_donante        VARCHAR2(20),
    id_centro         NUMBER,
    fecha             DATE,
    volumen_ml        NUMBER,
    estado            VARCHAR2(20),
    id_usuario_registra VARCHAR2(20),
    CONSTRAINT fk_donacion_donante FOREIGN KEY (id_donante)
        REFERENCES donante(id_donante),
    CONSTRAINT fk_donacion_centro FOREIGN KEY (id_centro)
        REFERENCES centro_donacion(id_centro),
    CONSTRAINT fk_donacion_usuario FOREIGN KEY (id_usuario_registra)
        REFERENCES usuario(id_usuario)
);

-- Tabla 7: Donación Componente
CREATE TABLE donacion_componente (
    id_donacion_componente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_donacion            NUMBER,
    id_componente          NUMBER,
    unidades               NUMBER,
    CONSTRAINT fk_don_comp_donacion FOREIGN KEY (id_donacion)
        REFERENCES donacion(id_donacion),
    CONSTRAINT fk_don_comp_componente FOREIGN KEY (id_componente)
        REFERENCES componente_sanguineo(id_componente)
);

-- Tabla 8: Componente Sanguíneo
CREATE TABLE componente_sanguineo (
    id_componente     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(50),
    descripcion       VARCHAR2(255)
);

-- Tabla 9: Inventario
CREATE TABLE inventario (
    id_inventario         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_componente         NUMBER,
    id_tipo_sangre        NUMBER,
    unidades_disponibles  NUMBER,
    fecha_actualiza       DATE,
    id_usuario_actualiza  VARCHAR2(20),
    CONSTRAINT fk_inv_componente FOREIGN KEY (id_componente)
        REFERENCES componente_sanguineo(id_componente),
    CONSTRAINT fk_inv_tipo_sangre FOREIGN KEY (id_tipo_sangre)
        REFERENCES tipo_sangre(id_tipo_sangre),
    CONSTRAINT fk_inv_usuario FOREIGN KEY (id_usuario_actualiza)
        REFERENCES usuario(id_usuario)
);

-- Tabla 10: Causa Rechazo
CREATE TABLE causa_rechazo (
    id_causa          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion       VARCHAR2(255)
);

-- Tabla 11: Rechazo
CREATE TABLE rechazo (
    id_rechazo        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_donacion       NUMBER,
    id_causa          NUMBER,
    observaciones     VARCHAR2(255),
    usuario_registra  VARCHAR2(20),
    CONSTRAINT fk_rechazo_donacion FOREIGN KEY (id_donacion)
        REFERENCES donacion(id_donacion),
    CONSTRAINT fk_rechazo_causa FOREIGN KEY (id_causa)
        REFERENCES causa_rechazo(id_causa),
    CONSTRAINT fk_rechazo_usuario FOREIGN KEY (usuario_registra)
        REFERENCES usuario(id_usuario)
);

-- Tabla 12: Bitácora
CREATE TABLE bitacora (
    id_bitacora       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario        VARCHAR2(20),
    accion            VARCHAR2(50),
    fecha_hora        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    detalle           VARCHAR2(500),
    CONSTRAINT fk_bitacora_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);